language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
install:
  - npm install -g firebase-tools
  - npm install
script:
  - npm run build
after_success:
  - firebase deploy --project emersonchores --token 1/UgOhlM1Vj8CGWj7UWK7j3k5FwUYxjGVWU5tZZiA_Z81RPPQDDRP4ANTVdR1txbOA
